sjpegi.h: always use SJPEG_HAS_BUILTIN
Instead of `__has_builtin` directly.

Fixes build failure with compilers that don't define `__has_builtin`,
like `cl.exe`:

```
sjpegi.h(99,19): error C1012: unmatched parenthesis: missing ')'
```